In [1]:
import pyarrow.parquet as pq
import pyarrow as pa

In [5]:
df=pq.read_table(r"Y:\PROJECT\Renu\ILC_2024\Testing_EUWS\Results\ILC\BE\ILC2024_EUWS_PLA_WI_EP_BE_EUR_Losses\EP\Admin1_Lob\GU\ILC2024_EUWS_PLA_WI_EP_BE_EUR_EP_Admin1_Lob_GU_0.parquet").to_pandas()

In [6]:
df

,EPType,Loss,ReturnPeriod,Admin1Id,Admin1Name,LOBName,LOBId
0,OEP,4.252327e+07,10000.0,22525997,Brabant Wallon,AUTO,2
1,OEP,3.072026e+07,5000.0,22525997,Brabant Wallon,AUTO,2
2,OEP,1.591626e+07,1000.0,22525997,Brabant Wallon,AUTO,2
3,OEP,1.188185e+07,500.0,22525997,Brabant Wallon,AUTO,2
4,OEP,8.828825e+06,250.0,22525997,Brabant Wallon,AUTO,2
...,...,...,...,...,...,...,...
139,TCE-AEP,3.161450e+08,50.0,22525998,Vlaams Brabant,SPER,5
140,TCE-AEP,2.155147e+08,25.0,22525998,Vlaams Brabant,SPER,5
141,TCE-AEP,1.245959e+08,10.0,22525998,Vlaams Brabant,SPER,5
142,TCE-AEP,7.853886e+07,5.0,22525998,Vlaams Brabant,SPER,5
143,TCE-AEP,3.813824e+07,2.0,22525998,Vlaams Brabant,SPER,5

In [7]:
df22=pq.read_table(r"D:\RISHIN\TESTING\TEST_3\ILC2024_EUWS_PLA_WI_EP_BE_EUR_Losses\processing\Resolution Added\PLT_0_100.parquet").to_pandas()

In [8]:
df22

,LocationId,LocationName,LobName,LobId,PeriodId,EventId,Weight,EventDate,LossDate,Region,Peril,Loss,ADDRESSID,Admin1Id,Admin1Name,CrestaId,CrestaName
0,883578,BE_AGR_7133,AGR,1,5,53863678,0.000004,2020-01-05,2020-01-05,EU,WS,5.601156e+02,883578,7153299,Hainaut,60344327,7
1,883529,BE_AGR_4140,AGR,1,8,53876196,0.000004,2020-01-27,2020-01-27,EU,WS,1.880944e+04,883529,7153300,Liege,60344324,4
2,883583,BE_AGR_7533,AGR,1,5,53863678,0.000004,2020-01-05,2020-01-05,EU,WS,7.928736e+02,883583,7153299,Hainaut,60344327,7
3,911623,BE_AGR_7534,AGR,1,5,53863678,0.000004,2020-01-05,2020-01-05,EU,WS,7.236297e+03,911623,7153299,Hainaut,60344327,7
4,943056,BE_AGR_7910,AGR,1,5,53863678,0.000004,2020-01-05,2020-01-05,EU,WS,1.023584e+02,943056,7153299,Hainaut,60344327,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16580603,933343,BE_CAR_3832,AUTO,2,9497,53858319,0.000004,2020-03-03,2020-03-03,EU,WS,6.643455e+02,933343,7153301,Limburg,60344323,3
16580604,903899,BE_COM_4653,COM,3,3321,53871525,0.000004,2020-09-20,2020-09-20,EU,WS,6.110502e+03,903899,7153300,Liege,60344324,4
16580605,914531,BE_RSFD_2630,SPER,5,9495,53856487,0.000004,2020-09-12,2020-09-12,EU,WS,1.898770e+06,914531,7153308,Antwerpen,60344322,2
16580606,884027,BE_COM_4031,COM,3,3306,53884900,0.000004,2020-12-28,2020-12-28,EU,WS,1.428879e+05,884027,7153300,Liege,60344324,4
16580607,943494,BE_COM_4452,COM,3,3322,53874477,0.000004,2020-12-06,2020-12-06,EU,WS,2.176942e+04,943494,7153300,Liege,60344324,4